(function () {
  const text = new Map([
    ["Untitled.psd", "無題.psd"],
    ["Ready", "準備完了"],
    ["File", "ファイル"],
    ["New...", "新規..."],
    ["Open...", "開く..."],
    ["Place Embedded...", "埋め込み配置..."],
    ["Export PNG", "PNGを書き出し"],
    ["Export JPEG", "JPEGを書き出し"],
    ["Export PSD", "PSDを書き出し"],
    ["Revert", "復帰"],
    ["Edit", "編集"],
    ["Undo", "取り消し"],
    ["Step Backward", "1段階戻る"],
    ["Step Forward", "1段階進む"],
    ["Redo", "やり直し"],
    ["Cut", "カット"],
    ["Copy", "コピー"],
    ["Copy Merged", "結合部分をコピー"],
    ["Paste", "ペースト"],
    ["Paste Into", "選択範囲内へペースト"],
    ["Delete", "削除"],
    ["Fill...", "塗りつぶし..."],
    ["Content-Aware Fill...", "コンテンツに応じた塗りつぶし..."],
    ["Stroke...", "境界線..."],
    ["Fill Foreground", "描画色で塗りつぶし"],
    ["Fill Background", "背景色で塗りつぶし"],
    ["Image", "画像"],
    ["Image Size...", "画像解像度..."],
    ["Canvas Size...", "カンバスサイズ..."],
    ["Levels...", "レベル補正..."],
    ["Curves...", "トーンカーブ..."],
    ["Hue/Saturation...", "色相・彩度..."],
    ["Vibrance...", "自然な彩度..."],
    ["Color Balance...", "カラーバランス..."],
    ["Black & White...", "白黒..."],
    ["Exposure...", "露光量..."],
    ["Shadows/Highlights...", "シャドウ・ハイライト..."],
    ["Auto Tone", "自動トーン補正"],
    ["Auto Color", "自動カラー補正"],
    ["Auto Contrast", "自動コントラスト"],
    ["Invert", "階調の反転"],
    ["Desaturate", "彩度を下げる"],
    ["Threshold...", "2階調化..."],
    ["Posterize...", "ポスタリゼーション..."],
    ["Trim Transparent Pixels", "透明ピクセルをトリミング"],
    ["Reveal All", "すべて表示"],
    ["Rotate 180", "180度回転"],
    ["Rotate 90 CW", "90度時計回りに回転"],
    ["Rotate 90 CCW", "90度反時計回りに回転"],
    ["Flip Canvas Horizontal", "カンバスを左右反転"],
    ["Flip Canvas Vertical", "カンバスを上下反転"],
    ["Reset Adjustments", "調整をリセット"],
    ["Apply Visible Filters", "表示フィルターを適用"],
    ["New Adjustment Layer", "新規調整レイヤー"],
    ["Crop", "切り抜き"],
    ["Free Transform", "自由変形"],
    ["Filter", "フィルター"],
    ["Gaussian Blur...", "ぼかし（ガウス）..."],
    ["Box Blur...", "ボックスぼかし..."],
    ["Average", "平均"],
    ["Surface Blur...", "表面ぼかし..."],
    ["Smart Blur...", "ぼかし（詳細）..."],
    ["Radial Blur...", "ぼかし（放射状）..."],
    ["Twirl...", "渦巻き..."],
    ["Pinch...", "つまむ..."],
    ["Ripple...", "波紋..."],
    ["Spherize...", "球面..."],
    ["ZigZag...", "ジグザグ..."],
    ["Wave...", "波形..."],
    ["Polar Coordinates...", "極座標..."],
    ["Shear...", "シアー..."],
    ["Motion Blur...", "ぼかし（移動）..."],
    ["Sharpen", "シャープ"],
    ["Unsharp Mask...", "アンシャープマスク..."],
    ["Smart Sharpen...", "スマートシャープ..."],
    ["High Pass...", "ハイパス..."],
    ["Find Edges", "輪郭検出"],
    ["Oil Paint...", "油彩..."],
    ["Glowing Edges...", "光彩輪郭..."],
    ["Emboss...", "エンボス..."],
    ["Diffuse...", "拡散..."],
    ["Wind...", "風..."],
    ["Trace Contour...", "輪郭トレース..."],
    ["Extrude...", "押し出し..."],
    ["Tiles...", "タイル..."],
    ["Solarize", "ソラリゼーション"],
    ["Clouds", "雲模様"],
    ["Difference Clouds", "雲模様（差の絶対値）"],
    ["Lens Flare...", "逆光..."],
    ["Fibers...", "ファイバー..."],
    ["Lighting Effects...", "照明効果..."],
    ["Add Noise...", "ノイズを加える..."],
    ["Reduce Noise...", "ノイズを軽減..."],
    ["Despeckle", "ダスト除去"],
    ["Dust & Scratches...", "ダスト＆スクラッチ..."],
    ["Median...", "中央値..."],
    ["Color Halftone...", "カラーハーフトーン..."],
    ["Crystallize...", "水晶..."],
    ["Pointillize...", "点描..."],
    ["Fragment", "分割"],
    ["Facet", "面取り"],
    ["Mezzotint...", "メゾティント..."],
    ["Mosaic...", "モザイク..."],
    ["Offset...", "オフセット..."],
    ["Maximum...", "明るさの最大値..."],
    ["Minimum...", "明るさの最小値..."],
    ["Layer", "レイヤー"],
    ["New Layer", "新規レイヤー"],
    ["Layer Via Copy", "選択範囲をコピーしたレイヤー"],
    ["Layer Via Cut", "選択範囲をカットしたレイヤー"],
    ["Duplicate Layer", "レイヤーを複製"],
    ["Rename Layer...", "レイヤー名を変更..."],
    ["Layer from Background", "背景からレイヤーへ"],
    ["Background from Layer", "レイヤーから背景へ"],
    ["Delete Layer", "レイヤーを削除"],
    ["Rotate Layer 90 CW", "レイヤーを90度時計回りに回転"],
    ["Rotate Layer 90 CCW", "レイヤーを90度反時計回りに回転"],
    ["Flip Layer Horizontal", "レイヤーを左右反転"],
    ["Flip Layer Vertical", "レイヤーを上下反転"],
    ["Align Left Edges", "左端を揃える"],
    ["Align Horizontal Centers", "水平方向中央を揃える"],
    ["Align Right Edges", "右端を揃える"],
    ["Align Top Edges", "上端を揃える"],
    ["Align Vertical Centers", "垂直方向中央を揃える"],
    ["Align Bottom Edges", "下端を揃える"],
    ["Bring to Front", "最前面へ"],
    ["Bring Forward", "前面へ"],
    ["Send Backward", "背面へ"],
    ["Send to Back", "最背面へ"],
    ["Select Top Layer", "最上位レイヤーを選択"],
    ["Select Layer Above", "上のレイヤーを選択"],
    ["Select Layer Below", "下のレイヤーを選択"],
    ["Select Bottom Layer", "最下位レイヤーを選択"],
    ["Create Clipping Mask", "クリッピングマスクを作成"],
    ["Lock Transparent Pixels", "透明ピクセルをロック"],
    ["Lock Pixels", "ピクセルをロック"],
    ["Lock Position", "位置をロック"],
    ["Lock All", "すべてロック"],
    ["Add Reveal Mask", "表示マスクを追加"],
    ["Add Hide Mask", "非表示マスクを追加"],
    ["Disable/Enable Mask", "マスクを無効・有効"],
    ["Apply Mask", "マスクを適用"],
    ["Invert Mask", "マスクを反転"],
    ["Delete Layer Mask", "レイヤーマスクを削除"],
    ["Toggle Drop Shadow", "ドロップシャドウ切替"],
    ["Toggle Stroke", "境界線切替"],
    ["Toggle Outer Glow", "光彩（外側）切替"],
    ["Copy Layer Style", "レイヤースタイルをコピー"],
    ["Paste Layer Style", "レイヤースタイルをペースト"],
    ["Clear Layer Style", "レイヤースタイルを消去"],
    ["Rasterize Layer Style", "レイヤースタイルをラスタライズ"],
    ["Merge Down", "下のレイヤーと結合"],
    ["Stamp Visible", "表示レイヤーをスタンプ"],
    ["Merge Visible", "表示レイヤーを結合"],
    ["Flatten Image", "画像を統合"],
    ["Select", "選択"],
    ["All", "すべて"],
    ["Deselect", "選択を解除"],
    ["Reselect", "再選択"],
    ["Inverse", "選択範囲を反転"],
    ["Quick Mask", "クイックマスク"],
    ["Subject", "被写体"],
    ["Color Range...", "色域指定..."],
    ["Color Range", "色域指定"],
    ["Similar", "近似色"],
    ["Grow", "選択範囲を拡張"],
    ["Save Selection", "選択範囲を保存"],
    ["Load Alpha Channel", "アルファチャンネルを読み込み"],
    ["Feather...", "ぼかし..."],
    ["Smooth...", "滑らかに..."],
    ["Expand...", "拡張..."],
    ["Contract...", "縮小..."],
    ["Border...", "境界..."],
    ["View", "表示"],
    ["Actual Pixels", "ピクセル等倍"],
    ["Fit on Screen", "画面サイズに合わせる"],
    ["Zoom In", "ズームイン"],
    ["Zoom Out", "ズームアウト"],
    ["Show Rulers", "定規を表示"],
    ["Show Extras", "エクストラを表示"],
    ["Show Grid", "グリッドを表示"],
    ["Show Guides", "ガイドを表示"],
    ["Snap", "スナップ"],
    ["Snap to Grid", "グリッドにスナップ"],
    ["Snap to Guides", "ガイドにスナップ"],
    ["Toggle Panels", "パネル表示切替"],
    ["Toggle Tools and Panels", "ツールとパネル表示切替"],
    ["New Vertical Guide", "新規垂直ガイド"],
    ["New Horizontal Guide", "新規水平ガイド"],
    ["Clear Guides", "ガイドを消去"],
    ["Open", "開く"],
    ["Move Tool", "移動ツール"],
    ["Rectangular Marquee", "長方形選択ツール"],
    ["Magic Wand", "自動選択ツール"],
    ["Lasso Tool", "なげなわツール"],
    ["Pen Tool", "ペンツール"],
    ["Spot Healing Brush", "スポット修復ブラシ"],
    ["Clone Stamp", "コピースタンプ"],
    ["History Brush", "ヒストリーブラシ"],
    ["Gradient Tool", "グラデーションツール"],
    ["Shape Tool", "シェイプツール"],
    ["Smudge Tool", "指先ツール"],
    ["Dodge/Burn Tool", "覆い焼き・焼き込みツール"],
    ["Crop Tool", "切り抜きツール"],
    ["Brush Tool", "ブラシツール"],
    ["Eraser Tool", "消しゴムツール"],
    ["Type Tool", "文字ツール"],
    ["Eyedropper Tool", "スポイトツール"],
    ["Hand Tool", "手のひらツール"],
    ["Zoom Tool", "ズームツール"],
    ["Auto-Select", "自動選択"],
    ["Brush", "ブラシ"],
    ["Opacity", "不透明度"],
    ["Heal", "修復"],
    ["Tolerance", "許容値"],
    ["Selection", "選択範囲"],
    ["New", "新規"],
    ["Add", "追加"],
    ["Subtract", "削除"],
    ["Intersect", "共通範囲"],
    ["Contiguous", "隣接"],
    ["Sample All", "全レイヤーを対象"],
    ["Gradient", "グラデーション"],
    ["Linear", "線形"],
    ["Radial", "円形"],
    ["Reverse", "逆方向"],
    ["Shape", "シェイプ"],
    ["Rect", "長方形"],
    ["Ellipse", "楕円"],
    ["Fill", "塗り"],
    ["Stroke", "境界線"],
    ["Strength", "強さ"],
    ["Mode", "モード"],
    ["Dodge", "覆い焼き"],
    ["Burn", "焼き込み"],
    ["Text", "テキスト"],
    ["New text", "新しいテキスト"],
    ["Size", "サイズ"],
    ["Apply Crop", "切り抜きを適用"],
    ["Cancel", "キャンセル"],
    ["Clear Selection", "選択解除"],
    ["Fit", "全体表示"],
    ["Reset", "リセット"],
    ["Move", "移動"],
    ["Wand", "自動選択"],
    ["Lasso", "なげなわ"],
    ["Pen", "ペン"],
    ["Erase", "消去"],
    ["Stamp", "スタンプ"],
    ["Hist", "履歴"],
    ["Grad", "グラデ"],
    ["Smudge", "指先"],
    ["Tone", "補正"],
    ["Type", "文字"],
    ["Pick", "取得"],
    ["Hand", "手のひら"],
    ["Zoom", "ズーム"],
    ["Navigator", "ナビゲーター"],
    ["Histogram", "ヒストグラム"],
    ["Info", "情報"],
    ["Color", "カラー"],
    ["FG", "描画色"],
    ["BG", "背景色"],
    ["Swap", "入替"],
    ["Default", "初期値"],
    ["Channels", "チャンネル"],
    ["Red", "レッド"],
    ["Green", "グリーン"],
    ["Blue", "ブルー"],
    ["Save Sel", "選択保存"],
    ["Load Alpha", "アルファ読込"],
    ["Brush Presets", "ブラシプリセット"],
    ["Hard Round", "硬い円ブラシ"],
    ["Soft Round", "柔らかい円ブラシ"],
    ["Airbrush", "エアブラシ"],
    ["Square", "四角ブラシ"],
    ["Calligraphy", "カリグラフィ"],
    ["Hard", "硬い"],
    ["Soft", "柔らかい"],
    ["Air", "エア"],
    ["Ink", "インク"],
    ["Hardness", "硬さ"],
    ["Spacing", "間隔"],
    ["Flow", "流量"],
    ["Properties", "プロパティ"],
    ["Brightness", "明るさ"],
    ["Contrast", "コントラスト"],
    ["Saturation", "彩度"],
    ["Hue", "色相"],
    ["Gray", "グレー"],
    ["Blur", "ぼかし"],
    ["Filters", "フィルター"],
    ["Transform", "変形"],
    ["Rotate L", "左回転"],
    ["Rotate R", "右回転"],
    ["Flip X", "左右反転"],
    ["Flip Y", "上下反転"],
    ["Align L", "左揃え"],
    ["Align X", "水平中央"],
    ["Align R", "右揃え"],
    ["Align T", "上揃え"],
    ["Align Y", "垂直中央"],
    ["Align B", "下揃え"],
    ["Layer Style", "レイヤースタイル"],
    ["Raster", "ラスタライズ"],
    ["None", "なし"],
    ["Drop Shadow", "ドロップシャドウ"],
    ["Distance", "距離"],
    ["Shadow Color", "影の色"],
    ["Outer Glow", "光彩（外側）"],
    ["Glow", "光彩"],
    ["Glow Color", "光彩の色"],
    ["Layers", "レイヤー"],
    ["Dup", "複製"],
    ["Up", "上へ"],
    ["Down", "下へ"],
    ["Clip", "クリップ"],
    ["Del", "削除"],
    ["Blend", "描画モード"],
    ["Normal", "通常"],
    ["Darken", "比較（暗）"],
    ["Multiply", "乗算"],
    ["Color Burn", "焼き込みカラー"],
    ["Lighten", "比較（明）"],
    ["Screen", "スクリーン"],
    ["Color Dodge", "覆い焼きカラー"],
    ["Linear Dodge (Add)", "覆い焼き（リニア）加算"],
    ["Overlay", "オーバーレイ"],
    ["Soft Light", "ソフトライト"],
    ["Hard Light", "ハードライト"],
    ["Difference", "差の絶対値"],
    ["Exclusion", "除外"],
    ["Luminosity", "輝度"],
    ["Blend If", "ブレンド条件"],
    ["Target", "対象"],
    ["Pixels", "ピクセル"],
    ["Mask", "マスク"],
    ["Lock", "ロック"],
    ["No mask", "マスクなし"],
    ["Reveal", "表示"],
    ["Hide", "非表示"],
    ["Disable", "無効"],
    ["Apply", "適用"],
    ["Select All", "すべて選択"],
    ["Smooth", "滑らかに"],
    ["Expand", "拡張"],
    ["Contract", "縮小"],
    ["Border", "境界"],
    ["Fill FG", "描画色で塗る"],
    ["Fill BG", "背景色で塗る"],
    ["Content", "コンテンツ"],
    ["Feather", "ぼかし"],
    ["Paths", "パス"],
    ["No path", "パスなし"],
    ["Make Sel", "選択作成"],
    ["Clear", "消去"],
    ["History", "ヒストリー"],
    ["Snap", "スナップ"],
  ]);

  const phrase = [
    [/^FG (#[0-9a-f]{6})$/i, "描画色 $1"],
    [/^(\d+) selected px$/, "$1 px 選択中"],
    [/^(\d+) anchors$/, "$1 アンカー"],
    [/^(\d+) history states?$/, "履歴 $1 件"],
    [/^(\d+) styles?$/, "スタイル $1 件"],
    [/^Navigator (.+)$/, "ナビゲーター $1"],
  ];

  function translate(value) {
    const trimmed = value.trim();
    const translated = text.get(trimmed);
    if (translated) return value.replace(trimmed, translated);
    for (const [pattern, replacement] of phrase) {
      if (pattern.test(trimmed)) return value.replace(trimmed, trimmed.replace(pattern, replacement));
    }
    return value;
  }

  function localizeNode(root) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) node.nodeValue = translate(node.nodeValue);

    for (const element of root.querySelectorAll("[title], [aria-label]")) {
      for (const attr of ["title", "aria-label"]) {
        if (element.hasAttribute(attr)) element.setAttribute(attr, translate(element.getAttribute(attr)));
      }
    }
  }

  localizeNode(document.body);

  new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData") {
        const nextValue = translate(mutation.target.nodeValue);
        if (nextValue !== mutation.target.nodeValue) mutation.target.nodeValue = nextValue;
      }
      for (const node of mutation.addedNodes) {
        if (node.nodeType === Node.TEXT_NODE) node.nodeValue = translate(node.nodeValue);
        if (node.nodeType === Node.ELEMENT_NODE) localizeNode(node);
      }
    }
  }).observe(document.body, { childList: true, characterData: true, subtree: true });
})();
